config/routes.rb
Shirelist::Application.routes.draw do
  root :to => 'listings#index'
  resources :listings, :only => [:index, :new, :create, :show]

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :title, :description, :price, :listing_key

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController #inherits from ApplicationController
  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.create(params[:listing])
    listing_key = SecureRandom.urlsafe_base64 #this should be in the model and automatically done via callback
    @listing[:listing_key] = listing_key
    redirect_to listing_path(@listing.id) if @listing.save
  end

  def show
    @listing = Listing.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shirelist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Share+Tech' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Serif+Caption' rel='stylesheet' type='text/css'>
</head>
<body>
  <header>
    <div id = "nav-bar">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Login", root_path %></li>
        <li>
      </ul>
    </div>
  </header>
  <div id = "main-container">
   <%= yield %>
  </div>
</body>
</html>

app/views/listings/index.html.erb
<h2>Welcome to ShireList</h2>

<h3>Our Current Listings</h3>
<ul item = "listingslist">
<% @listings.each do |listing| %>
<li><%= listing.title %> <%= listing.description %> <%= listing.price %></li>
<% end %>
</ul>

<%= link_to "Create a new listing", new_listing_path %>

app/views/listings/new.html.erb
<h3>What would you like to list today? </h3>
<%= form_for @listing, html: {class: "listing_form"} do |f| %>
  <%= f.text_field :title, placeholder: "title" %><br />
  <%= f.text_area :description, size: "60x12", placeholder: "description" %><br />
  <%= f.text_field :price, placeholder: "price" %><br />
  <%= f.submit "Add Listing" %>
<% end %>

app/views/listings/show.html.erb
<h1>You have posted the following to ShireList</h1>

Title: <%= @listing.title %><br />
Description: <%= @listing.description %><br />
Price: <%= @listing.price %><br />